name: Monitor NC DMV Appointments

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Dependencies
        run: go mod download

      - name: Run ncdmv Monitor
        run: |
          go run ./cmd/ncdmv \
            --appt-type permit \
            --locations cary,durham-east,durham-south \
            --interval 5m \
            --headless \
            --discord-webhook "${{ secrets.DISCORD_WEBHOOK }}"
